### ISSUE TITLE
poetry does not install neo4j properly

### ISSUE THREAD

**Issue by tch1001** [TwigSlot/twig-server#1]
https://github.com/TwigSlot/twig-server/blob/8c2a53d129d1488c53ea7cf3f1c0827209eed0ea/twig_server/app.py#L1

i had to use pip install neo4j to fix this locally. i'm not sure why poetry can't get it right?

**Comment by tch1001** [comment]
im not sure if its just a me problem, because things like dotenv required manual installation too.

**Comment by bushshrub** [comment]
`poetry install` to install stuff lol

**Comment by bushshrub** [comment]
I set up a custom devcontainer configuration in the `dev` branch, try that.

**Comment by bushshrub** [comment]
Can we close this @tch1001
