### ISSUE TITLE
Better query system

### ISSUE THREAD

**Issue by bushshrub** [TwigSlot/twig-server#4]
Automatically proxy any cypher queries to the backend Neo4j server.

Should only occur after users have authenticated

**Comment by tch1001** [comment]
Hmm but I want people to be able to view the graph without logging in, just that they can only save if they log in. Perhaps we can have a read limit for the number of rows implemented in flask (just appending LIMIT 1000 in the cypher query should work). Nginx can handle malicious spam requests

**Comment by bushshrub** [comment]
If you want them to be able to view the graph without logging in we can't allow them to execute queries on the neo4j server arbitrarily since actually finding out what that code does is NP-hard (or probably even impossible)

**Comment by tch1001** [comment]
Right... ok guess we can expose an API to the client, and form the queries on server side. For a simple test let's do something like 
/:username -> MATCH (n:User) WHERE n.username = username RETURN n 
I'll implement more routes when I work on client side

**Comment by tch1001** [comment]
implemented as of this [commit](https://github.com/TwigSlot/twig-server/commit/c923956abeb0dbcdee34cb312fd3bf8ab191bab7)
